// Словники для тренажера.
// Кожен набір: { title, words: { "українською": "english" } }
// Дані відокремлені від логіки (див. js/main.js).

const LESSONS = {
	les1: {
		title: "Урок 1",
		words: {
			"Весілля": "wedding",
			"Прибути, приїхати": "arrive",
			"Включно": "including",
			"Королівський": "royal",
			"Важливий день": "the big day",
			"Запрошувати": "invite",
			"Справді": "really",
			"Голос": "voice",
			"Грабіжник": "burglar",
			"Сміятися": "laugh",
			"Кричати": "shout",
			"Спати": "be asleep",
			"Пояснювати": "explain",
			"Незручний": "embarrassing",
			"Вхідні двері": "front door",
			"Штовхати": "push",
			"Безсумнівно": "certainly",
			"Вийти": "walk out",
			"Футболка": "T-shirt",
			"Светр": "sweater",
			"Краватка": "tie",
			"Спідниця": "skirt",
			"Пальто": "coat",
		},
	},
	les2: {
		title: "Урок 2",
		words: {
			"Народитися": "be born",
			"Шум": "noise",
			"Увімкнути": "turn on",
			"Можливий": "possible",
			"Пам’ятати": "remember",
			"Зовсім": "at all",
			"Вітальня": "sitting room",
			"Скло, склянка": "glass",
			"Бути впевненим": "be sure",
			"Бути закоханим": "be in love with",
			"Залишати": "leave",
			"Бути тупим": "be stupid",
			"Заміський будинок": "country house",
			"Вуса": "mustache",
			"Зала": "living room",
			"Опівночі": "midnight",
			"Слідувати за": "follow",
			"Відділяти": "separate",
		},
	},
	les3: {
		title: "Урок 3",
		words: {
			"Посудомийна машина": "dishwasher",
			"Шампанське": "champagne",
			"Вбивство": "murder",
			"Коханець": "lover",
			"Ванна кімната": "bathroom",
			"Спальня": "bedroom",
			"Їдальня": "dining room",
			"Гараж": "garage",
			"Коридор": "hall",
			"Стеля": "ceiling",
			"Поверх": "floor",
			"Сходи": "stairs",
			"Плита": "cooker",
			"Шафа для посуду": "cupboard",
			"Камін": "fireplace",
			"Пральна машина": "washing machine",
			"Підозрілий": "suspicious",
			"Орендувати": "rent",
			"гардероб": "wardrobe",
		},
	},
	les4: {
		title: "Урок 4",
		words: {
			"Небагато": "a little bit",
			"Моторошний": "spooky",
			"Пульт": "remote control",
			"Фільм жахів": "horror film",
			"Раптово": "suddenly",
			"Бути наляканим(1)": "be scared",
			"По троху": "little by little",
			"Бути наляканим(2)": "be frightened",
			"Безумовно": "definitely",
			"Привид": "ghost",
			"Хоробрий": "brave",
			"Священик": "priest",
			"З’являтися": "appear",
			"Позаду": "behind",
			"Власник": "owner",
			"Гість": "guest",
			"Виписатися": "check out",
			"ЗAмок": "castle",
			"Перед": "in front of",
			"Під": "under",
			"Протилежний": "opposite",
			"Поряд з": "next to",
			"Над": "over",
			"Від до": "from to",
			"Всередині": "into",
			"За межами": "outside",
			"Назустріч": "towards",
		},
	},
	les5: {
		title: "Урок 5",
		words: {
			"Рецепт": "recipe",
			"Змагання": "competition",
			"Випуск, видання": "edition",
			"Аплодисменти": "applause",
			"Учасник": "contestant",
			"Основна страва": "main course",
			"Окремо": "apart",
			"Крем-сир": "cream cheese",
			"скуштувати": "taste",
			"Смачно": "delicious",
			"Страва": "dish",
			"Стейк": "steak",
			"Закуска": "snack",
			"Звичка": "habit",
			"Незвичайний": "unusual",
			"З собою": "take away",
			"Уявити": "imagine",
			"Взяти": "pick up",
			"Каша": "porridge",
			"Миска": "bowl",
			"Суворий": "strict",
			"Грудка": "breast",
			"Солодка кукурудза": "sweet corn",
			"Величезний": "enormous",
			"Вершки": "cream",
			"Увесь день": "whole day",
			"Злаки, мюслі": "cereal",
			"Тост(їжа)": "toast",
			"Шинка": "ham",
			"листя салату": "lettuce",
			"Гриб": "mushroom",
			"Горох": "pea",
			"Ананас": "pineapple",
			"Печиво": "biscuit",
			"Чіпси": "crisps",
		},
	},
	les6: {
		title: "Урок 6",
		words: {
			"Приголомшливий": "fascinating",
			"Плавання": "voyage",
			"Вага": "weight",
			"Давній": "ancient",
			"Шахта": "mine",
			"Спливти": "float",
			"Паливо": "fuel",
			"Замість чогось": "instead of",
			"Пральний порошок": "washing powder",
			"Утримувати": "contain",
			"Вимовляти": "pronounce",
			"Чайна ложка": "teaspoon",
			"Бляшана банка": "can",
			"Картон": "carton",
			"Банка": "jar",
			"Консервна банка": "tin",
			"Повна ложка": "spoonful",
			"Газований": "fizzy",
		},
	},
	les7: {
		title: "Урок 7",
		words: {
			"Декілька варіантів відповідей": "multiple choice",
			"Загальний": "general",
			"знання": "knowledge",
			"Аудиторія, публіка": "audience",
			"Зменшити": "reduce",
			"Бути одержимим": "be obsessed",
			"Дрібниці": "trivia",
			"Бити": "beat",
			"Перевірити ще раз": "double-check",
			"Приблизний": "approximate",
			"Нервувати": "be nervous",
			"Середній": "average",
			"Тяжкий": "heavy",
			"Здоровий": "healthy",
			"Жіноча стать": "female",
			"Чоловіча стать": "male",
			"Комар": "mosquito",
			"Кусати": "bite",
			"Ремінь, пояс": "belt",
			"Час майже закінчився": "time is nearly up",
		},
	},
	les8: {
		title: "Урок 8",
		words: {
			"Широкий": "wide",
			"Нижче": "below",
			"Дорожньо-транспортна пригода": "accident",
			"Заявляти": "declare",
			"З того часу": "since",
			"Вантажівка": "lorry",
			"Захоплюючий": "exciting",
			"Над(2)": "above",
			"Майже(2)": "nearly",
			"Вузький": "narrow",
			"Сезон дощів": "rainy season",
			"Досвідчений": "experienced",
			"Брати участь": "take part",
			"Наляканий": "scared",
			"Впасти": "fall",
			"Парковка": "car park",
			"Універмаг": "department store",
			"Мечеть": "mosque",
			"Залізнична станція": "railway station",
			"Торговий центр": "mall",
			"Храм": "temple",
			"Мерія": "town hall",
		},
	},
	les9: {
		title: "Урок 9",
		words: {
			"Господар": "host",
			"Сусід по квартирі": "flatmate",
			"Млинці": "crepes",
			"Кран (з якого тече)": "tap",
			"Зійти з потягу": "get off the train",
			"Нереальний": "surreal",
			"Кушетка": "couch",
			"Каучсерфінг": "couchsurfing",
			"Повністю": "completely",
			"Створити профіль": "create a profile",
			"Вирішувати вам.": "it's up to you",
			"Насправді": "in fact",
		},
	},
	les10: {
		title: "Урок 10",
		words: {
			"сперечатися": "argue",
			"Залишитися разом": "stay together",
			"Перевернути": "turn over",
			"Ще один, інший": "another",
			"Зосередитись": "concentrate",
			"Привабливий": "attractive",
			"Чітко, ясно": "clearly",
		},
	},
	les11: {
		title: "Урок 11",
		words: {
			"Їсти не вдома (в ресторані)": "eat out",
			"Іноземець": "foreigner",
			"Особливо": "especially",
			"Бездоганний": "immaculate",
			"Достатньо": "quite",
			"В наші дні": "nowadays",
			"Ідеально": "perfectly",
			"Дерев’яний": "wooden",
			"Ввічливий": "polite",
			"Щоденно": "daily",
			"Дивовижно": "incredibly",
		},
	},
	les12: {
		title: "Урок 12",
		words: {
			"Скласти, пройти тест": "pass",
			"Жахливий": "terrible",
			"Піти у відставку": "retire",
			"Амбіції": "ambitions",
			"Звичайний, банальний": "trivial",
			"Відповідати(2)": "respond",
			"Підбиратися": "climb",
			"Роман": "novel",
			"Не спати": "be awake",
			"Слова пісні": "lyrics",
			"Видалити з системи": "uninstall",
			"Вимова": "pronunciation",
			"Давай! Роби!, Дій!": "go for it",
			"Смажений": "roast",
			"Переважно": "preferably",
		},
	},
	les13: {
		title: "Урок 13",
		words: {
			"Аукціон": "auction",
			"Виявити": "find out",
			"Схуднути": "lose weight",
			"Переказ грошей": "transfer",
			"Вкладення": "attachment",
			"Шукати": "search for",
			"Соціальна мережа": "social network",
		},
	},
	les14: {
		title: "Урок 14",
		words: {
			"Затемнення": "eclipse",
			"Мити": "wash",
			"Посуд": "dishes",
			"Принаймі": "at least",
			"Бути ситим": "be full",
			"Стосунки": "relationship",
			"Будь-коли": "whenever",
			"Правильно": "properly",
		},
	},
	les15: {
		title: "Урок 15",
		words: {
			"північ(місце)": "north",
			"недавній": "recent",
			"Спроможність": "ability",
			"Охайний": "tidy",
			"Зробити відкриття, віднайти": "discover",
			"Сільська місцевість": "countryside",
		},
	},
	les16: {
		title: "Урок 16",
		words: {
			"Мати на увазі (дієсл.), жадібний(прикм.)": "mean",
			"слідувати": "follow",
			"Протягом": "during",
			"майже ніколи": "hardly ever",
			"Піти прогулятися": "go out",
			"Хімія": "chemistry",
			"Нарешті": "at last",
			"Щотижневий": "weekly",
			"Товариський": "sociable",
			"Почуття гумору": "sense of humor",
			"Хлопець": "guy",
			"Сумісний": "compatible",
			"Домашні тварини": "pets",
			"Котрий?": "which",
			"Кучерявий": "curly",
			"Прямий": "straight",
			"Хвилястий": "wavy",
			"Борода": "beard",
			"Лисий": "bald",
			"Худий": "thin",
			"Трохи": "a bit",
			"З зайвою вагою": "overweight",
			"Середнього зросту": "medium height",
			"Говіркий": "talkative",
			"Працьовитий": "hard-working",
			"Тихий": "quiet",
		},
	},
	les17: {
		title: "Урок 17",
		words: {
			"Розглядати": "consider",
			"Приблизно": "approximately",
			"Ціль": "aim",
			"Невірність": "infidelity",
			"Розлучитись": "divorce",
			"Вагітна": "pregnant",
			"Кардиган": "cardigan",
			"Сукня": "dress",
			"Куртка": "jacket",
			"Чоботи": "boots",
			"Сорочка": "shirt",
			"Штани": "trousers",
			"Костюм": "suit",
			"Спортивний костюм": "tracksuit",
			"Легінси (лосини)": "leggings",
			"Шльопанці": "flip-flops",
			"Кросівки": "trainers",
			"Рукавички": "gloves",
			"Шарф": "scarf",
			"Колготки": "tights",
			"Сережки": "earrings",
			"Намисто": "necklace",
			"Обручка": "ring",
			"Ювелірні прикраси": "jewellery",
		},
	},
	les18: {
		title: "Урок 18",
		words: {
			"Боротися": "fight",
			"Обкладинка журнала": "cover of magazine",
			"Помічати": "notice",
			"вибори": "election",
			"Напружений": "tense",
			"Бути проголошеним": "be announced",
			"Божевільний": "mad",
		},
	},
	les19: {
		title: "Урок 19",
		words: {
			"Хоча": "although",
			"Гальма": "brake",
			"Увійти, сісти в машину": "get in",
			"Нетерпляче чекати": "look forward to",
			"Річниця": "anniversary",
			"Панікувати": "panic",
		},
	},
	my: {
		title: "Мої слова",
		words: {
			"майже": "almost",
			"племінник": "nephew",
			"свічка": "candle",
			"сторінка": "page",
			"речення": "sentence",
			"вибір": "choice",
			"торт": "cake",
			"залишатися": "stay",
			"більшість": "majority",
			"іноземний": "foreign",
			"захворювання": "disease",
			"дія": "action",
			"шлях": "way",
			"причина": "reason",
			"впевнений": "sure",
			"просто, тільки": "just",
			"килим": "carpet",
			"подарунок": "gift",
			"полиця": "shelf",
			"навушники": "earphones",
			"цибуля": "onion",
			"теплий": "warm",
			"відповідати": "reply",
			"гучний": "noisy",
			"грубий": "rude",
			"дивуватись": "wonder",
			"запрошення": "invitation",
			"діра": "hole",
			"зошит": "copybook",
			"неважливо": "doesn't matter",
			"втомлюватись": "get tired",
			"догляд, дбайливість": "care",
			"байдуже": "don't care",
			"до якогось моменту": "until",
			"біль": "pain",
			"коліно": "knee",
			"щока": "cheek",
			"сором'язливий": "shy",
			"груша": "pear",
			"очікувати": "expect",
			"позичати": "borrow",
			"збентежити": "embarrass",
			"припускати": "suppose",
			"забрати": "pick up",
			"чверть на 7": "quarter to seven",
			"дослідження": "research",
			"пара": "couple",
			"сусід": "neighbor",
			"бідолашний": "poor",
			"сухий": "dry",
			"відмовити": "refuse",
			"втікати": "escape",
			"описувати": "describe",
			"ймовірно": "probably",
			"страшно": "scary",
			"заздрити": "envy",
			"подорож": "journey",
			"ретельно": "carefully",
			"жук": "beetle",
			"трава": "grass",
			"кістка": "bone",
			"рости": "grow",
			"неймовірно": "incredible",
			"буряк": "beet",
			"точний": "exact",
			"переконати": "convince",
			"вибачитися": "apologize",
			"належить": "belong",
			"заслуговувати": "deserve",
			"переконання": "belief",
			"застряг": "stuck",
			"вибачення": "apology",
			"точно": "exactly",
			"гордий": "proud",
			"насправді(2)": "actually",
			"принести": "bring",
			"лікувати": "treat",
			"захоплюватись кимось": "admire",
			"колега по роботі": "coworker",
			"тимчасовий": "temporary",
			"зізнаватись": "confess",
			"класти": "put",
			"підняти": "raise",
			"дорослий": "adult",
			"нагадати": "remind",
			"їзда на велосипеді": "cycling",
			"сором": "shame",
			"персонал": "staff",
			"уникати": "avoid",
			"пропонувати": "suggest",
			"монета": "coin",
			"залучати": "involve",
			"припускати(2)": "assume",
			"щедрий": "generous",
			"дихати": "breathe",
			"довіра": "trust",
			"хіба що": "unless",
			"наливати": "pour",
			"вгадати": "guess",
			"гаманець": "purse",
			"подушка": "pillow",
			"задоволений": "satisfied",
			"близнюк": "twin",
			"недавно": "recently",
			"все одно": "anyway",
			"зброя": "weapon",
			"доступний": "available",
			"доступ": "access",
			"крім": "except",
			"чесний": "honest",
			"дозволяти": "allow",
			"гнів": "anger",
			"діяти": "act",
			"глибокий": "deep",
			"на жаль": "unfortunately",
			"мені шкода": "i regret",
			"скромний": "humble",
			"оборона": "defense",
			"в жодному разі": "no way",
			"йде сніг": "snowing",
			"унікальний": "unique",
			"досліджувати": "explore",
			"пригода": "adventure",
			"досягти": "achieve",
			"розійтись": "break up",
			"шия": "neck",
			"град": "hail",
			"яскравий": "bright",
			"рідко": "rarely",
			"конкретний": "specific",
			"графік": "schedule",
			"навантаження": "load",
			"метро": "underground",
			"сторона": "side",
			"часник": "garlic",
			"держава": "state",
			"закон": "law",
			"справа": "case",
			"забезпечити": "provide",
			"служити": "serve",
			"залишатись(2)": "remain",
			"низький": "low",
			"подібний": "similar",
			"різні": "various",
			"працівник": "employee",
			"розваги": "entertainment",
			"банда": "gang",
			"просунутий": "advanced",
			"голосувати": "vote",
			"справедливо": "fairly",
			"несправедливо": "unfairly",
			"ковдра": "blanket",
			"найняти": "hire",
			"прийняти": "accept",
			"вражає": "impressive",
			"застосувати": "apply",
			"роботодавець": "employer",
			"гордий за": "proud of",
			"обійми": "hug",
			"пропозиція": "suggest",
			"відхилити": "reject",
			"шукати": "seek",
			"в іншому місці": "elsewhere",
			"працевлаштування": "employment",
			"понаднормово": "overtime",
			"зміна(робоча)": "shift",
			"сприяти": "promote",
			"понизити (на посаді)": "demote",
			"згадка": "mention",
			"побачення": "date",
			"ювілей": "anniversary",
			"завдання": "task",
			"сила": "strength",
			"відповідальний": "responsible",
			"слабкість": "weakness",
			"здогадатися": "figure out",
			"Через (пройти через щось)": "through",
			"відправлення": "departure",
			"отримати": "receive",
			"на щастя": "fortunately",
			"захистити": "protect",
			"Падіння": "drop",
			"чувак": "dude",
			"приятель": "buddy",
			"кохана": "sweetheart",
			"пательня": "frying pan",
			"вилка": "fork",
			"чайник": "kettle",
			"Стрункий": "slim",
			"Зебра": "zebra",
			"замОк": "lock",
			"пропустити": "miss",
			"розвивати": "develop",
			"будь ласка": "you're welcome",
			"тиша": "silence",
			"Голуб": "dove",
			"Зникати": "vanish",
			"Кинути, розкидати": "throw",
			"Мило(засіб)": "soap",
			"пилосос": "vacuum cleaner",
			"пилососити": "vacuum",
			"Носки": "socks",
			"Конкретно": "specifically",
			"На мою думку": "in my opinion",
			"Схвильований": "excited",
			"Стурбований": "worried",
			"Туман": "fog",
			"Винахід": "invention",
			"голитись": "shave",
			"Співпадіння": "coincidence",
			"зовнішній вигляд": "appearance",
			"Дитинство": "childhood",
			"Розбити": "smash",
			"Увага": "attention",
			"Умова": "condition",
			"Етап": "stage",
			"вирішувати": "resolve",
			"обожнювати": "adore",
			"бажання": "desire",
			"Здаватись": "give up",
			"Полум'я": "flame",
			"нести": "carry",
			"зручний (в користуванні)": "convenient",
			"білка": "squirrel",
			"наука": "science",
			"вчений": "scientist",
			"заряд (батареї)": "charge",
		},
	},
	// ── 3000 Must Know Words (за категоріями) ─────────────────────────────────

	book_1: {
		title: "Риси та особистості",
		words: {
			"надійний": "reliable",
			"старанний": "diligent",
			"розумний": "intelligent",
			"терплячий": "patient",
			"щедрий": "generous",
			"скромний": "humble",
			"впевнений у собі": "self-confident",
			"раціональний": "sensible",
			"амбітний": "ambitious",
			"сміливий": "courageous",
			"вірний": "loyal",
			"спостережливий": "observant",
			"чарівний": "charming",
			"дотепний": "witty",
			"ненадійний": "unreliable",
			"лінивий": "lazy",
			"неосвічений": "ignorant",
			"зарозумілий": "arrogant",
			"сором'язливий": "timid",
			"нечесний": "dishonest",
			"імпульсивний": "impulsive",
			"тривожний": "anxious",
			"боягузливий": "cowardly",
			"дратівливий": "irritable",
			"впертий": "stubborn",
			"жорстокий": "cruel",
			"довірливий": "gullible",
			"поверхневий": "superficial",
		},
	},

	book_2: {
		title: "Зовнішній вигляд",
		words: {
			"привабливий": "attractive",
			"красивий (про чоловіка)": "handsome",
			"дуже красивий": "gorgeous",
			"приголомшливий вигляд": "stunning",
			"стильний": "stylish",
			"добре одягнений": "well-dressed",
			"зморшки": "wrinkles",
			"веснянки": "freckles",
			"щетина": "stubble",
			"колір обличчя": "complexion",
			"засмагла": "tanned",
			"з блідою шкірою": "pale-skinned",
			"шрам": "scar",
			"опухлі очі": "puffy eyes",
			"темні кола під очима": "dark circles",
			"прямий ніс": "straight nose",
			"ніс гачком": "hooked nose",
			"курносий": "snub-nosed",
			"зачіска": "hairstyle",
			"хвіст (зачіска)": "ponytail",
			"коса (зачіска)": "braid",
			"лисий": "bald",
			"каштанове волосся": "chestnut hair",
			"руде волосся": "ginger hair",
			"світле волосся": "fair hair",
			"спортивний (статура)": "athletic",
			"міцний": "well-built",
			"м'язистий": "muscular",
			"струнка": "slim",
			"з надмірною вагою": "overweight",
			"що страждає на ожиріння": "obese",
		},
	},

	book_3: {
		title: "Емоції",
		words: {
			"веселий": "amused",
			"задоволений": "delighted",
			"захоплений": "thrilled",
			"радісний": "joyful",
			"вдоволений": "content",
			"пригнічений": "depressed",
			"розчарований": "disappointed",
			"засмучений": "frustrated",
			"розбитий розпачем": "heartbroken",
			"розбитий горем": "devastated",
			"здивований": "astonished",
			"остовпілий": "stunned",
			"збитий з пантелику": "confused",
			"переляканий": "frightened",
			"дуже переляканий": "terrified",
			"вражений жахом": "horrified",
			"роздратований": "annoyed",
			"розлючений": "furious",
			"ображений": "offended",
		},
	},

	book_4: {
		title: "Відносини",
		words: {
			"близький друг": "close friend",
			"товариш": "buddy",
			"знайомий": "acquaintance",
			"познайомитися": "get to know",
			"мати багато спільного": "have a lot in common",
			"віддалятися": "drift apart",
			"неодружений/незаміжня": "single",
			"пара": "couple",
			"побачення наосліп": "blind date",
			"закохатися": "fall in love",
			"зробити пропозицію": "propose",
			"бути зарученим": "be engaged",
			"наречений/наречена": "fiancé",
			"рідний брат/сестра": "sibling",
			"вітчим/мачуха": "stepparent",
			"родичі чоловіка/дружини": "in-laws",
			"дитинство": "childhood",
			"малюк": "toddler",
			"підліток": "teenager",
			"дорослий": "adult",
			"середніх років": "middle-aged",
		},
	},

	book_5: {
		title: "Здоров'я",
		words: {
			"втома": "fatigue",
			"непритомніти": "faint",
			"запаморочення": "dizzy",
			"тиск (кров'яний)": "blood pressure",
			"мати алергію на": "be allergic to",
			"грип": "flu",
			"лихоманка": "fever",
			"запалення": "inflammation",
			"серцевий напад": "heart attack",
			"біль у горлі": "sore throat",
			"кашель": "cough",
			"симптом": "symptom",
			"перша допомога": "first aid",
			"діагноз": "diagnosis",
			"рецепт (ліки)": "prescription",
			"болезаспокійливе": "painkiller",
			"щеплення": "vaccination",
			"операція": "surgery",
		},
	},

	__mistakes__: {
		title: "⚠ Складні",
		words: {},
	},
};

if (typeof window !== "undefined") {
	window.LESSONS = LESSONS;
}
